class Autogenerated {
  String? patientId;
  String? patientName;
  String? patientAge;
  String? patientPhone;
  String? classification;
  String? description;
  String? ownerid;

  Autogenerated(
      {this.patientId,
        this.patientName,
        this.patientAge,
        this.patientPhone,
        this.classification,
        this.description,
        this.ownerid});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    patientId = json['patientId'];
    patientName = json['patientName'];
    patientAge = json['patientAge'];
    patientPhone = json['patientPhone'];
    classification = json['classification'];
    description = json['description'];
    ownerid = json['ownerid'];
  }

}
