class Autogenerated {
  List<Data>? data;

  Autogenerated({this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(new Data.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Data {
  String? patientId;
  String? patientName;
  String? patientAge;
  String? patientPhone;
  String? classification;
  String? description;
  String? ownerid;

  Data(
      {this.patientId,
        this.patientName,
        this.patientAge,
        this.patientPhone,
        this.classification,
        this.description,
        this.ownerid});

  Data.fromJson(Map<String, dynamic> json) {
    patientId = json['patientId'];
    patientName = json['patientName'];
    patientAge = json['patientAge'];
    patientPhone = json['patientPhone'];
    classification = json['classification'];
    description = json['description'];
    ownerid = json['ownerid'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['patientId'] = this.patientId;
    data['patientName'] = this.patientName;
    data['patientAge'] = this.patientAge;
    data['patientPhone'] = this.patientPhone;
    data['classification'] = this.classification;
    data['description'] = this.description;
    data['ownerid'] = this.ownerid;
    return data;
  }
}
