import 'dart:convert';

import 'package:doctor_application/models/newmode.dart';
import 'package:get/get.dart';
import 'package:http/http.dart' as http;
class homescreencontroller extends GetxController{

getdata()async{
  @override
  void onInit(){
   getdata();
  }
  Autogenerated? autogenerated;
  http.Response response = await http.get(Uri.parse("http://160.20.146.238/api?action=listRecords"));
  Map<String,dynamic>data=jsonDecode(response.body);
  autogenerated = Autogenerated.fromJson(data);
  print(autogenerated!.description);
  update();
}
}
